version: '3'

services:
  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '27016:27017'
    volumes:
      - data:/data/db


volumes: 
  data:
    name: dad-project-managers-settings-volume


